# Generated by Django 5.2.16 on 2026-08-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_demo_account',
            field=models.BooleanField(default=False),
        ),
    ]
