# Generated by Django 5.2.16 on 2026-08-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_showcase_mode', models.BooleanField(default=False, help_text='Enables frictionless signup (no email verification) and auto-seeds demo data. Demo accounts are reset every 24 hours.')),
                ('is_maintenance_mode', models.BooleanField(default=False, help_text='When enabled, all non-admin API requests return a 503 Service Unavailable.')),
                ('allow_registrations', models.BooleanField(default=True, help_text='If disabled, new users cannot register.')),
                ('default_from_email', models.EmailField(blank=True, help_text="Default 'From' email address for Apprise email notifications.", max_length=254, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_user', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_pass', models.CharField(blank=True, max_length=255, null=True)),
                ('max_monitors_per_org', models.IntegerField(default=50, help_text='Global limit for monitors per organization.')),
                ('data_retention_days', models.IntegerField(default=90, help_text='Days to keep raw check data before it is rolled up into statistics.')),
                ('minimum_check_interval', models.IntegerField(default=20, help_text='Minimum allowed monitor check interval in seconds.')),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
