# Generated by Django 6.0.6 on 2026-06-29 13:14

from django.db import migrations, models
from django.conf import settings


def insert_default_roles(apps, scheme_editor):
    OrganizationRole = apps.get_model('organizations', 'OrganizationRole')

    OrganizationRole.objects.bulk_create([
        OrganizationRole(name="admin"),
        OrganizationRole(name="member")

    ])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_created_at_organization_updated_at_and_more'),
    ]

    operations = [
        migrations.RunPython(insert_default_roles, migrations.RunPython.noop)
    ]
