# Generated by Django 6.0.6 on 2026-07-02 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_prepopulate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='organizations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization'),
        ),
    ]
