# Generated by Django 5.2.16 on 2026-07-09 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0007_alter_organization_id_alter_organizationmember_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('webhook', 'Webhook'), ('discord', 'Discord')], default='email', max_length=20)),
                ('config', models.JSONField(default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_channels', to='organizations.organization')),
            ],
            options={
                'db_table': 'surveillance_alertchannel',
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('token_hash', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surveillance_apitoken',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='organizations.organization')),
            ],
            options={
                'db_table': 'surveillance_incident',
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=20)),
                ('message', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='surveillance.incident')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'surveillance_incidentupdate',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('interval', models.IntegerField(default=60, help_text='Check interval in seconds')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD')], default='GET', max_length=10)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('expected_status_codes', models.IntegerField(default=200)),
                ('timeout_ms', models.IntegerField(default=30000)),
                ('follow_redirect', models.BooleanField(default=True)),
                ('last_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded')], default='up', max_length=20)),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_monitors', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='organizations.organization')),
            ],
            options={
                'db_table': 'surveillance_monitor',
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='surveillance.monitor'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('rate_limited', 'Rate Limited')], default='sent', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('alert_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='surveillance.alertchannel')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='surveillance.incident')),
            ],
            options={
                'db_table': 'surveillance_notificationlog',
            },
        ),
        migrations.CreateModel(
            name='StatusPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.TextField()),
                ('title', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=20)),
                ('custom_domain', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_pages', to='organizations.organization')),
            ],
            options={
                'db_table': 'surveillance_statuspage',
            },
        ),
        migrations.CreateModel(
            name='StatusPageMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField(default=0)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_page_entries', to='surveillance.monitor')),
                ('status_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_monitors', to='surveillance.statuspage')),
            ],
            options={
                'db_table': 'surveillance_statuspagemonitor',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_token', models.TextField()),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('status_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='surveillance.statuspage')),
            ],
            options={
                'db_table': 'surveillance_subscriber',
            },
        ),
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ssl_valid', models.BooleanField(blank=True, null=True)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='surveillance.monitor')),
            ],
            options={
                'db_table': 'surveillance_apilog',
                'indexes': [models.Index(fields=['monitor', '-created_at'], name='surveillanc_monitor_86c45e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonitorRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='surveillance.monitor')),
            ],
            options={
                'db_table': 'surveillance_monitorregion',
                'unique_together': {('monitor', 'region')},
            },
        ),
    ]
