# Generated by Django 6.0.6 on 2026-06-28 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('webhook', 'Webhook'), ('discord', 'Discord')], default='email', max_length=20)),
                ('config', models.JSONField()),
                ('is_enabled', models.BooleanField()),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_organization', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('token_hash', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=20)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('major', 'Major'), ('critical', 'Critical')], default='minor', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_organizations', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('investigating', 'Investigating'), ('identified', 'Identified'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], default='investigating', max_length=20)),
                ('message', models.TextField()),
                ('posted_at', models.DateTimeField()),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='surveillance.incident')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archive', 'Archive')], default='active', max_length=20)),
                ('interval', models.IntegerField(null=True)),
                ('http_method', models.CharField(choices=[('get', 'Get'), ('post', 'Post'), ('put', 'Put'), ('delete', 'Delete')], default='get', max_length=20)),
                ('request_headers', models.JSONField()),
                ('request_body', models.JSONField(null=True)),
                ('expected_status_codes', models.IntegerField()),
                ('timeout_ms', models.IntegerField()),
                ('follow_redirect', models.BooleanField()),
                ('last_status', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('degraded', 'Degraded')], default='up', max_length=20)),
                ('consecutive_failures', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='monitor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='surveillance.monitor'),
        ),
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('response_time', models.IntegerField()),
                ('region', models.CharField(max_length=20)),
                ('error_message', models.TextField()),
                ('ssl_valid', models.BooleanField()),
                ('ssl_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('monitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apiLog_monitors', to='surveillance.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='monitorRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('monitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_monitors', to='surveillance.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('rate_limited', 'Rated_Limited')], default='sent', max_length=20)),
                ('error_message', models.TextField()),
                ('alert_channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='surveillance.alertchannel')),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_log', to='surveillance.incident')),
            ],
        ),
        migrations.CreateModel(
            name='StatusPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.TextField()),
                ('title', models.TextField()),
                ('is_public', models.BooleanField()),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='auto', max_length=20)),
                ('custom_domain', models.TextField(null=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_organization', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='StatusPageMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.IntegerField()),
                ('monitor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuspage_monitor', to='surveillance.monitor')),
                ('status_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuspages', to='surveillance.statuspage')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('webhook_url', models.URLField(null=True)),
                ('verified', models.BooleanField()),
                ('verification_token', models.TextField()),
                ('subscribed_at', models.DateTimeField()),
                ('status_page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuspagemonitors', to='surveillance.statuspagemonitor')),
            ],
        ),
    ]
