# Generated by Django 6.0.6 on 2026-07-02 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statuspage',
            old_name='organization_id',
            new_name='organization',
        ),
    ]
