# Generated by Django 5.2.16 on 2026-08-03 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_schema_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='degraded_threshold_ms',
            field=models.IntegerField(blank=True, help_text='Responses slower than this mark the monitor degraded.', null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='interval',
            field=models.IntegerField(default=60, help_text='Check interval in seconds (minimum 20).', validators=[django.core.validators.MinValueValidator(20)]),
        ),
        migrations.CreateModel(
            name='MonitorHourlyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True, help_text='Truncated to the hour, UTC.')),
                ('total_checks', models.IntegerField(default=0)),
                ('failed_checks', models.IntegerField(default=0)),
                ('degraded_checks', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(blank=True, null=True)),
                ('min_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('max_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('p50_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('p95_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('p99_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_stats', to='surveillance.monitor')),
            ],
            options={
                'db_table': 'surveillance_monitorhourlystat',
                'indexes': [models.Index(fields=['monitor', '-hour'], name='hourly_monitor_hour_idx')],
                'unique_together': {('monitor', 'hour')},
            },
        ),
    ]
