# Generated by Django 5.2.16 on 2026-08-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0003_engine_scaling'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='connect_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apilog',
            name='dns_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apilog',
            name='tls_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apilog',
            name='ttfb_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='MonitorRegion',
        ),
    ]
