# Generated by Django 5.2.16 on 2026-08-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0004_timings_and_drop_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertchannel',
            name='type',
            field=models.CharField(choices=[('slack', 'Slack'), ('discord', 'Discord'), ('webhook', 'Webhook'), ('apprise', 'Apprise (200+ services)')], default='email', max_length=20),
        ),
    ]
