# Generated by Django 5.2.16 on 2026-08-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0005_apprise_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='dns_expected',
            field=models.TextField(blank=True, help_text='Expected record value.'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='dns_record_type',
            field=models.CharField(blank=True, default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='monitor',
            name='heartbeat_grace_seconds',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='monitor',
            name='heartbeat_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='monitor',
            name='json_expected',
            field=models.TextField(blank=True, help_text='Value that path must equal.'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='json_path',
            field=models.TextField(blank=True, help_text='Dotted path into the JSON body, e.g. data.status'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='keyword',
            field=models.TextField(blank=True, help_text='Text the response body must contain.'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='keyword_inverted',
            field=models.BooleanField(default=False, help_text='Fail when the keyword IS present instead.'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='last_heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='port',
            field=models.IntegerField(blank=True, help_text='TCP port monitors.', null=True),
        ),
        migrations.AddField(
            model_name='monitor',
            name='type',
            field=models.CharField(choices=[('http', 'HTTP(S)'), ('keyword', 'Keyword in body'), ('json', 'JSON query'), ('ping', 'Ping (ICMP)'), ('port', 'TCP port'), ('dns', 'DNS record'), ('ssl', 'SSL certificate'), ('domain', 'Domain expiry'), ('heartbeat', 'Heartbeat (push)')], default='http', max_length=20),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
