# Generated by Django 5.2.16 on 2026-08-03 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_organization_id_alter_organizationmember_id_and_more'),
        ('surveillance', '0006_monitor_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspage',
            name='password_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='unsubscribe_token',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('suppress_alerts', models.BooleanField(default=True)),
                ('exclude_from_uptime', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to=settings.AUTH_USER_MODEL)),
                ('monitors', models.ManyToManyField(blank=True, related_name='maintenance_windows', to='surveillance.monitor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='organizations.organization')),
            ],
            options={
                'db_table': 'surveillance_maintenancewindow',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['organization', '-starts_at'], name='maint_org_starts_idx')],
            },
        ),
    ]
