# Generated by Django 5.2.16 on 2026-08-26 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_organization_id_alter_organizationmember_id_and_more'),
        ('surveillance', '0007_status_page_phase_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertchannel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='incidentupdate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='maintenancewindow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monitorhourlystat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statuspage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='statuspagemonitor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.CharField(help_text='Stable unique identifier from the probe.', max_length=64, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('region', models.CharField(db_index=True, max_length=50)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('capabilities', models.JSONField(default=list, help_text='List of supported check types.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null if a global public probe.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='organizations.organization')),
            ],
            options={
                'db_table': 'surveillance_probe',
            },
        ),
        migrations.CreateModel(
            name='ProbeHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('queue_utilization', models.FloatField(blank=True, null=True)),
                ('clock_offset_ms', models.IntegerField(blank=True, null=True)),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='surveillance.probe')),
            ],
            options={
                'db_table': 'surveillance_probeheartbeat',
            },
        ),
        migrations.CreateModel(
            name='ProbeToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('prefix', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='surveillance.probe')),
            ],
            options={
                'db_table': 'surveillance_probetoken',
            },
        ),
    ]
