# Generated by Django 5.2.16 on 2026-08-26 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0008_alter_alertchannel_id_alter_apilog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='probes',
            field=models.ManyToManyField(blank=True, related_name='monitors', to='surveillance.probe'),
        ),
        migrations.CreateModel(
            name='ProbeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField(db_index=True)),
                ('dispatched_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probe_assignments', to='surveillance.monitor')),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='surveillance.probe')),
            ],
            options={
                'db_table': 'surveillance_probeassignment',
                'indexes': [models.Index(fields=['probe', 'due_at'], name='probe_assignment_due_idx')],
                'unique_together': {('probe', 'monitor', 'due_at')},
            },
        ),
    ]
