# Generated by Django 5.2.16 on 2026-08-26 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_organization_id_alter_organizationmember_id_and_more'),
        ('surveillance', '0009_monitor_probes_probeassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_policies', to='organizations.organization')),
            ],
            options={
                'db_table': 'surveillance_escalationpolicy',
            },
        ),
        migrations.CreateModel(
            name='EscalationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_minutes', models.IntegerField(default=0, help_text='Wait time before executing this step.')),
                ('target_type', models.CharField(choices=[('user', 'User'), ('schedule', 'Schedule'), ('channel', 'Channel')], max_length=20)),
                ('target_id', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='surveillance.escalationpolicy')),
            ],
            options={
                'db_table': 'surveillance_escalationstep',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='OnCallSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_zone', models.CharField(default='UTC', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='organizations.organization')),
            ],
            options={
                'db_table': 'surveillance_oncallschedule',
            },
        ),
    ]
