# Generated by Django 5.2.16 on 2026-08-26 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_alter_organization_id_alter_organizationmember_id_and_more'),
        ('surveillance', '0010_incident_acknowledged_at_incident_commander_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLevelObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('target_percentage', models.FloatField(default=99.9)),
                ('window_days', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monitors', models.ManyToManyField(blank=True, related_name='slos', to='surveillance.monitor')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slos', to='organizations.organization')),
            ],
            options={
                'db_table': 'surveillance_servicelevelobjective',
            },
        ),
    ]
