# Generated by Django 5.2.16 on 2026-08-26 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0011_servicelevelobjective'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='script_content',
            field=models.TextField(blank=True, help_text='Playwright/JS script content for browser/script checks.'),
        ),
        migrations.CreateModel(
            name='Postmortem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Markdown content detailing root cause, timeline, and lessons learned.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='postmortem', to='surveillance.incident')),
            ],
            options={
                'db_table': 'surveillance_postmortem',
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('postmortem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='surveillance.postmortem')),
            ],
            options={
                'db_table': 'surveillance_correctiveaction',
            },
        ),
        migrations.CreateModel(
            name='StatusComponentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('status_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_groups', to='surveillance.statuspage')),
            ],
            options={
                'db_table': 'surveillance_statuscomponentgroup',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='StatusComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('operational', 'Operational'), ('degraded_performance', 'Degraded Performance'), ('partial_outage', 'Partial Outage'), ('major_outage', 'Major Outage'), ('under_maintenance', 'Under Maintenance')], default='operational', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('linked_monitors', models.ManyToManyField(blank=True, related_name='linked_components', to='surveillance.monitor')),
                ('status_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='surveillance.statuspage')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='surveillance.statuscomponentgroup')),
            ],
            options={
                'db_table': 'surveillance_statuscomponent',
                'ordering': ['display_order'],
            },
        ),
    ]
