# Generated by Django 5.2.16 on 2026-08-26 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0012_monitor_script_content_postmortem_correctiveaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='escalation_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitors', to='surveillance.escalationpolicy'),
        ),
    ]
