# Generated by Django 5.2.16 on 2026-08-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0014_alter_alertchannel_config_alter_monitor_request_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
